delete from artist;
INSERT INTO artist VALUES ('1','Mahogany Rush','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('2','Elf','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('3','Mehitabel','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('4','Big Brother and The Holding Company','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('5','Roy Harper','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('6','Pat Benatar','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('7','Rory Gallagher','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('8','Iron Maiden','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('9','Blaster Bates','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('10','Procol Harum','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('11','1000 Maniacs','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('12','Wishbone Ash','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('13','Nazareth','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('14','Crosby Stills Nash and Young','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('15','George Thorogood and The Destroyers','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('16','Axel Rudi Pell','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('17','Leaf Hound','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('18','Budgie','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('19','Commitments','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('20','Enigma','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('21','Kevin Bloody Wilson','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('22','Pixies','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('23','ZZ Top','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('24','Pressgang','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('25','Hayseed Dixie','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('26','Paco De Lucia','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('27','Ted Nugent','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('28','Hawkwind','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('29','Status Quo','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('30','Dusty Springfield','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('31','Soundtracks','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('32','Dream Theater','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('33','Peter Gabriel','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('34','Imelda May','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('35','Dio','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('36','Black Sabbath','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('37','Dr Feelgood','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('38','Carole King','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('39','Heart','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('40','Chopyn','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('41','Darkness','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('42','Jimmy Page and Robert Plant','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('43','Vangelis','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('44','Black Oak Arkansas','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('45','Lou Reed','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('46','Oasis','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('47','Manfred Mann','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('48','Tomita','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('49','Mood Elevator','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('50','Warner E Hodges','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('51','Be Bop Deluxe','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('52','Ozric Tentacles','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('53','Florence And The Machine','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('54','Bon Jovi','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('55','Jefferson Airplane','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('56','Rolling Stones','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('57','Mountain','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('58','Guess Who','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('59','Vladimir Vysotsky','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('60','Frank Zappa Captain Beefheart and The Mothers','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('61','Steve Vai','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('62','Black River Project','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('63','Treatment','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('64','Led Zeppelin','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('65','Bruce Springsteen','Nicknamed "The Boss", Springsteen is an American singer-songwriter and rock musician, widely known for his brand of poetic lyrics.');
INSERT INTO artist VALUES('66','AC DC','AC/DC are Australia''s most successful rock band ever, and are popular around the world.');
INSERT INTO artist VALUES('67','Velvet Underground','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('68','Man','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('69','Animals','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('70','Prokofiev','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('71','Thin Lizzy','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('72','Blackbeard''s Tea Party','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('73','Arlo Guthrie','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('74','Ry Cooder','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('75','Leatherat','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('76','Ozzy Osbourne','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('77','Jefferson Starship','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('78','Smetana','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('79','Extreme','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('80','Ian Gillan','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('81','Lone Star','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('82','Uriah Heep','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('83','John Lee Hooker','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('84','Van Halen','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('85','John Martyn','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('86','10cc','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('87','Rachel Portman','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('88','Jakatta','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('89','Pearl Jam','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('90','Jimi Hendrix','A self-taught guitarist, internationally acclaimed as a premier rock musician and innovator of his generation.');
INSERT INTO artist VALUES('91','Kate Bush','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('92','Fleetwood Mac','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('93','Foo Fighters','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('94','Robert Calvert','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('95','New Model Army','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('96','Steppenwolf','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('97','Camel','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('98','Beth Orton','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('99','Tom Lehrer','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('100','Michael Moorcock and the Deep Fix','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('101','Free','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('102','The Clan','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('103','Madonna','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('104','Allan Holdsworth','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('105','David Bowie','British pop/rock singer, musician, songwriter, and actor. Bowie is recognized as one of the most respected contemporary musicians of his period. ');
INSERT INTO artist VALUES('106','Judas Priest','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('107','Steely Dan','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('108','Ennio Morricone','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('109','Terry Reid','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('110','Dread Zeppelin','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('111','Mumford and Sons','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('112','Emerson Lake and Palmer','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('113','Horslips','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('114','Blue Öyster Cult','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('115','UFO','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('116','Genesis','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('117','Lenny Kravitz','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('118','Primordial Soup','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('119','Bob Marley','Marley remains the most widely known and revered performer of reggae music.');
INSERT INTO artist VALUES('120','Carl Orff','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('121','The Killers','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('122','O.S.T.','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('123','White Zombie','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('124','Bonzo Dog Band','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('125','Evanescence','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('126','Cream','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('127','Tom Jones','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('128','Edvard Grieg','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('129','Meredith Brooks','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('130','Pink Floyd','Founded in 1965, the group achieved worldwide acclaim, initially with innovative psychedelic music, and later in a genre that came to be termed progressive rock. ');
INSERT INTO artist VALUES('131','King Crimson','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('132','Joe Bonamassa','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('133','Black Keys','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('134','Dire Straits','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('135','Bernie Torme','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('136','Velvet Revolver','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('137','Doors','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('138','Richard Ashcroft','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('139','Bo Didley','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('140','Frank Zappa','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('141','Mussorgsky','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('142','Faith No More','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('143','Meat Loaf','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('144','Neutrons','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('145','B.B. King','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('146','Joe Satriani','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('147','Thunder','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('148','Yardbirds','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('149','Gorillaz','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('150','Foreigner','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('151','J.J. Cale','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('152','Aerosmith','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('153','Troggs','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('154','Biffy Clyro','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('155','Howlin'' Wolf','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('156','Marillion','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('157','Stone Roses','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('158','Clannad','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('159','Jeff Buckley','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('160','Rainbow','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('161','Corey Taylor','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('162','Kula Shaker','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('163','Bachman Turner Overdrive','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('164','Captain Beefheart','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('165','Eric Serra','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('166','Eric Clapton','Prolific English blues-rock guitarist, singer and composer affectionately known as "Slow Hand".');
INSERT INTO artist VALUES('167','Chumbawamba','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('168','Grover Washinton Jr','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('169','Guns N'' Roses','Guns N'' Roses is an American hard rock band formed in 1985 in Los Angeles, California.');
INSERT INTO artist VALUES('170','Steve Harley and Cockney Rebel','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('171','Queen','Queen is a British rock band formed in London in 1970. One of the world''s best-selling music artists.');
INSERT INTO artist VALUES('172','Sweet','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('173','Steve Hillage','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('174','Iggy Pop','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('175','Seasick Steve','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('176','Billy Idol','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('177','Split Whiskers','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('178','Alice Cooper','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('179','Yngwie Malmsteen','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('180','Steve Hackett','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('181','Beatles','British rock/pop group, formed in Liverpool, England during the late 1950s. Inducted into Rock And Roll Hall of Fame in 1988 (Group).');
INSERT INTO artist VALUES('182','DragonForce','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('183','Jools Holland','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('184','Gary Moore','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('185','Heaven and Hell','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('186','Paul Giovanni','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('187','John Paul Jones','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('188','Billy Joel','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('189','Bad Company','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('190','Patti Smith','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('191','Black Crowes','A pop rock artist from USA who burst on into popular music stardom in the 70s.');
INSERT INTO artist VALUES('192','Metallica','Thrash Metal (Heavy Metal) band from Los Angeles, California (USA). ');
INSERT INTO artist VALUES('193','U2','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('194','Garbage','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('195','Pink Fairies','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('196','Deep Purple','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('197','T.Rex','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('198','Tom Petty and The Heartbreakers','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('199','Thomas Tallis','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('200','Stevie Ray Vaughan','Emerging on to the western musical scene in the 90s, this band is renowned for having a pleasing musical sensibility and powerful, energetic live shows.');
INSERT INTO artist VALUES('201','Chemical Brothers','Emerging on to the western musical scene in the 90s, this band is 
renowned for having a pleasing musical sensibility and powerful, energetic live shows.');	